### ISSUE TITLE
how to delete a sandbox image?

### ISSUE THREAD

**Issue by hoosierEE** [eecs-autograder/autograder-contrib#7]
My main goal is to remove some sandbox images that are no longer used at my organization, as the drop-down menu in the web interface is getting cluttered with no-longer-used sandboxes.

To achieve this goal, I attempted to extend the existing commands in `sandbox_docker_image.py` with my own `delete` command, but I get this error:

```shell
[autograder@gadget autograder-contrib]$ ./sandbox_docker_image.py --base_url=https://autograder.example.edu/ delete 18
{'detail': 'Method "DELETE" not allowed.'}
Traceback (most recent call last):
  File "./sandbox_docker_image.py", line 183, in <module>
    main()
  File "./sandbox_docker_image.py", line 35, in main
    delete_image(client, args.pk)
  File "./sandbox_docker_image.py", line 40, in delete_image
    http_client.check_response_status(response)
  File "/opt/autograder/autograder-contrib/ag_contrib/http_client.py", line 85, in check_response_status
    response.raise_for_status()
  File "/l/python3/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://autograder.example.edu/api/sandbox_docker_images/18/
```

The `create`, `edit` etc. commands all succeed for me, so maybe this is a configuration issue, but I don't know where to look. Any help appreciated.

Here's the code I added to `sandbox_docker_image.py`:

```python
def delete_image(client: http_client.HTTPClient, pk: int):
    response = client.delete(f'/api/sandbox_docker_images/{pk}/')
    http_client.check_response_status(response)

    print(image_to_str(response.json()))
```

**Comment by hoosierEE** [comment]
Ah, I think I found an explanation. My fork predates [this commit](https://github.com/eecs-autograder/autograder-server/commit/5ffc363ca33804f0039c19f86d100d6e5c8a9cc1#diff-35c21a80e3599a7f39c3dbe8f0bb5b42) so there's no delete available.
